name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Convert deb to IPA
        run: |
          curl -L -o ${{ github.workspace }}/app.deb "${{ github.event.inputs.deb }}"
          dpkg-deb -X ${{ github.workspace }}/app.deb ${{ github.workspace }}/app

          mkdir -p ${{ github.workspace }}/ipa/Payload
          cp -R ${{ github.workspace }}/app/Applications/* ${{ github.workspace }}/ipa/Payload
          
          cd ${{ github.workspace }}/ipa
          zip -r ${{ github.workspace }}/App.ipa .

      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: App
          path: ${{ github.workspace }}/App.ipa

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          # Nom de l'artefact (modifiable, par défaut "artifact")
          name: artifact
          # Chemin vers le fichier, dossier ou pattern à uploader
          path: ./path/to/artifact
          # Comportement si aucun fichier n'est trouvé : warn, error ou ignore
          if-no-files-found: warn
          # Nombre de jours de rétention (min 1, max 90)
          retention-days: 30
          # Niveau de compression (0 = aucune, 6 = compression par défaut, 9 = meilleure compression)
          compression-level: 6
          # Remplacer un artefact existant ? (false par défaut)
          overwrite: false
          # Inclure ou non les fichiers cachés (false par défaut)
          include-hidden-files: false
